function [time, data] = importfile(fileToRead1)
%IMPORTFILE(FILETOREAD1)
%  Imports data from the specified file
%  FILETOREAD1:  file to read

%  Auto-generated by MATLAB on 13-Jan-2014 13:51:35

DELIMITER = ',';
HEADERLINES = 0;

% Import the file
newData1 = importdata(fileToRead1, DELIMITER, HEADERLINES);

data = newData1.data;
time_split = regexp(newData1.textdata, ':', 'split');

time_min = 0;
for i=1:size(time_split)
    hours = str2num(cell2mat(time_split{i,1}(1,1))) * 60;
    minutes = str2num(cell2mat(time_split{i,1}(1,2))) ;
    seconds = str2num(cell2mat(time_split{i,1}(1,3))) / 60;
    if i==1
        time_min = hours+minutes+seconds;
    end
    time(i,1) = hours + minutes + seconds - time_min;
end


